package reports;

import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;

import java.io.File;
import java.util.Collections;
import java.util.List;

public class ReportGenerator {

    public static void main(String[] args) {
        // Path to where cucumber.json is generated by your TestRunner
        File reportOutputDirectory = new File("target/cucumber-report");

        // JSON file generated by Cucumber
        List<String> jsonFiles = Collections.singletonList("target/cucumber.json");

        // Project name shown in the report
        String projectName = "TestSolutionsWebsite-Testing-project";

        // Configuration for the report
        Configuration configuration = new Configuration(reportOutputDirectory, projectName);

        // Optional metadata
        configuration.addClassifications("Platform", "Windows 11");
        configuration.addClassifications("Browser", "Chrome");
        configuration.addClassifications("Branch", "master");

        // Generate the report
        ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
        reportBuilder.generateReports();
    }
}
